import type { Club, ClubMember, IndustrySeat } from '@/types/club'

// ─── MEMBERS ──────────────────────────────────────────────────────────────────

export const CLUB_MEMBERS: ClubMember[] = [
  {
    id: 'member-1',
    name: 'Garrett Hammonds',
    slug: 'garrett-hammonds',
    businessName: 'Hammonds Media',
    industry: 'Web Design & Digital Marketing',
    industrySlug: 'web-design-digital-marketing',
    role: 'President',
    shortBio: 'Garrett helps local businesses build their online presence through strategic web design and digital marketing.',
    bio: 'Garrett Hammonds is the founder of Hammonds Media, a full-service digital marketing and web design agency serving small and mid-sized businesses across Oklahoma. With over a decade of experience building websites and running digital campaigns, Garrett brings a data-driven approach to every project. He joined ThinkBiz.Solutions because he believes strongly in the power of referral relationships — most of his best clients started as a warm introduction from someone he trusted. He currently serves as Chapter President of the OKC North chapter.',
    avatar: '/assets/illustrations/excitement-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/garretthammonds',
    website: 'https://hammondsmedia.com',
    phone: '405-555-0101',
    memberSince: '2022-01-15',
    clubSlugs: ['okc-north'],
    specialties: ['Website Design', 'SEO', 'Google Ads', 'Social Media Marketing'],
    testimonial: 'ThinkBiz has been one of the single best business decisions I have made. The referrals I receive from my chapter generate more revenue per dollar than any ad campaign I have run.',
  },
  {
    id: 'member-2',
    name: 'Sarah Martinez',
    slug: 'sarah-martinez',
    businessName: 'Martinez Accounting Group',
    industry: 'Accounting / CPA',
    industrySlug: 'accounting-cpa',
    role: 'Vice President',
    shortBio: 'Sarah is a licensed CPA specializing in small business accounting, tax strategy, and bookkeeping for service-based businesses.',
    bio: 'Sarah Martinez founded Martinez Accounting Group after spending eight years in public accounting at a regional firm. She works exclusively with small business owners, helping them understand their numbers, reduce their tax burden, and build financial systems that scale. Sarah has been a ThinkBiz member since the OKC North chapter launched and currently serves as Vice President. Her straightforward, no-jargon approach to accounting has earned her referrals from virtually every member of her chapter.',
    avatar: '/assets/illustrations/leadership-growth.svg',
    linkedin: 'https://www.linkedin.com/in/sarahmartinezcpa',
    website: 'https://martinezaccounting.com',
    memberSince: '2022-01-15',
    clubSlugs: ['okc-north'],
    specialties: ['Small Business Tax', 'Bookkeeping', 'QuickBooks', 'Business Formation'],
    testimonial: 'The structured format of ThinkBiz keeps referrals moving consistently. I have built relationships in my chapter that I expect to last my entire career.',
  },
  {
    id: 'member-3',
    name: 'James Whitfield',
    slug: 'james-whitfield',
    businessName: 'Whitfield Business Law',
    industry: 'Attorney — Business Law',
    industrySlug: 'attorney-business-law',
    role: 'Member',
    shortBio: 'James is a business attorney focusing on contracts, entity formation, and commercial transactions for Oklahoma entrepreneurs.',
    bio: 'James Whitfield has been practicing business law in Oklahoma City for over 15 years. His firm, Whitfield Business Law, handles everything from LLC and corporation formation to complex commercial contracts and business acquisitions. James joined ThinkBiz because he saw how many of his existing clients were connected to one another — and wanted a structured environment to turn those connections into a reliable referral system. He is known in his chapter for giving thoughtful, specific referrals and always following up.',
    avatar: '/assets/illustrations/follow-the-leader-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/jameswhitfieldlaw',
    memberSince: '2022-03-10',
    clubSlugs: ['okc-north'],
    specialties: ['Contract Review', 'Business Formation', 'Mergers & Acquisitions', 'Commercial Leases'],
  },
  {
    id: 'member-4',
    name: 'Priya Patel',
    slug: 'priya-patel',
    businessName: 'Patel Insurance Solutions',
    industry: 'Business & Commercial Insurance',
    industrySlug: 'business-commercial-insurance',
    role: 'Member',
    shortBio: 'Priya specializes in commercial insurance packages for small businesses, including general liability, BOP, and workers\' comp.',
    bio: 'Priya Patel is an independent insurance broker with over ten years of experience placing commercial coverage for small businesses throughout Oklahoma. She represents multiple carriers, which lets her find competitive rates without being locked into a single company\'s products. Priya joined ThinkBiz after a colleague recommended it and has since become one of the most active referral givers in her chapter. She genuinely enjoys connecting people and considers relationship-building the most rewarding part of her work.',
    avatar: '/assets/illustrations/team-work-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/priyapatelinsurance',
    memberSince: '2022-06-01',
    clubSlugs: ['okc-north'],
    specialties: ['General Liability', 'Business Owner Policy', 'Workers\' Comp', 'Commercial Auto'],
    testimonial: 'I was skeptical about structured networking at first. Now I cannot imagine running my book of business without it.',
  },
  {
    id: 'member-5',
    name: 'Brandon Cole',
    slug: 'brandon-cole',
    businessName: 'Cole Realty Group',
    industry: 'Real Estate — Residential',
    industrySlug: 'real-estate-residential',
    role: 'Member',
    shortBio: 'Brandon is a top-producing residential real estate agent serving the greater Oklahoma City metro area.',
    bio: 'Brandon Cole has been selling residential real estate in the OKC metro for nine years and consistently ranks among the top agents at his brokerage. He joined ThinkBiz because he recognized that the most sustainable real estate businesses are built on referral relationships, not paid leads. Brandon is known for his thorough market knowledge and his genuine interest in helping clients make sound decisions — not just quick ones.',
    avatar: '/assets/illustrations/business-flying.svg',
    linkedin: 'https://www.linkedin.com/in/brandoncoleokc',
    memberSince: '2023-02-01',
    clubSlugs: ['okc-north'],
    specialties: ['Buyer Representation', 'Seller Representation', 'First-Time Buyers', 'Investment Properties'],
  },
  {
    id: 'member-6',
    name: 'Lisa Tran',
    slug: 'lisa-tran',
    businessName: 'Tran Mortgage Group',
    industry: 'Mortgage / Home Loans',
    industrySlug: 'mortgage-home-loans',
    role: 'Secretary',
    shortBio: 'Lisa is a mortgage loan officer helping homebuyers navigate conventional, FHA, VA, and USDA loan programs.',
    bio: 'Lisa Tran has been originating home loans in Oklahoma for over twelve years. She joined ThinkBiz because she works in close proximity to real estate agents, financial planners, and insurance professionals — and found that the structured referral model created natural, accountable partnerships with all of them. Lisa serves as chapter Secretary and is well known for the educational "mortgage minute" she delivers at every meeting to keep the chapter up to date on rate changes and lending trends.',
    avatar: '/assets/illustrations/excitement-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/lisatranmortgage',
    memberSince: '2022-09-15',
    clubSlugs: ['okc-north'],
    specialties: ['Conventional Loans', 'FHA', 'VA Loans', 'USDA', 'Pre-Approval'],
  },
  {
    id: 'member-7',
    name: 'Rachel Kim',
    slug: 'rachel-kim',
    businessName: 'Kim Financial Planning',
    industry: 'Financial Planning & Wealth Management',
    industrySlug: 'financial-planning-wealth-management',
    role: 'Member',
    shortBio: 'Rachel is a fee-only financial planner helping clients build wealth, plan for retirement, and protect their families.',
    bio: 'Rachel Kim is a CFP® professional and founder of Kim Financial Planning, a fee-only advisory practice serving individuals and small business owners. Her approach centers on clear, conflict-free advice — she does not earn commissions on products she recommends. Rachel joined ThinkBiz because she found that her ideal clients were already connected to mortgage professionals, CPAs, and attorneys in the organization. The cross-referral relationships she has built within her chapter have become the foundation of her client acquisition strategy.',
    avatar: '/assets/illustrations/leadership-growth.svg',
    linkedin: 'https://www.linkedin.com/in/rachelkimcfp',
    memberSince: '2023-05-01',
    clubSlugs: ['okc-north'],
    specialties: ['Retirement Planning', 'Investment Management', 'Estate Planning Coordination', 'Business Owner Planning'],
  },
  {
    id: 'member-8',
    name: 'David Nguyen',
    slug: 'david-nguyen',
    businessName: 'Nguyen Roofing & Exteriors',
    industry: 'Roofing & Exterior Services',
    industrySlug: 'roofing-exterior-services',
    role: 'President',
    shortBio: 'David runs a full-service roofing and exterior company serving homeowners and commercial properties across central Oklahoma.',
    bio: 'David Nguyen founded Nguyen Roofing & Exteriors after working in the industry for over a decade under other contractors. His company handles residential and commercial roofing, siding, gutters, and storm damage claims. David joined ThinkBiz South because he wanted structured access to real estate agents, insurance professionals, and other contractors who regularly encounter homeowners in need of exterior work. He currently serves as Chapter President and is one of the most consistent referral contributors in the group.',
    avatar: '/assets/illustrations/team-work-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/davidnguyenroofing',
    memberSince: '2023-01-10',
    clubSlugs: ['okc-south'],
    specialties: ['Residential Roofing', 'Commercial Roofing', 'Storm Damage', 'Gutters & Siding'],
    testimonial: 'I have more than tripled my referral revenue since joining ThinkBiz South. The relationships in this group are real.',
  },
  {
    id: 'member-9',
    name: 'Amara Williams',
    slug: 'amara-williams',
    businessName: 'Williams Estate Law',
    industry: 'Attorney — Estate Planning',
    industrySlug: 'attorney-estate-planning',
    role: 'Vice President',
    shortBio: 'Amara is an estate planning attorney helping families protect their assets, plan for the future, and navigate probate.',
    bio: 'Amara Williams has been practicing estate planning law in Oklahoma for eleven years. Her firm, Williams Estate Law, helps individuals and families create wills, trusts, powers of attorney, and comprehensive estate plans that protect what they have built. Amara joined ThinkBiz South because she saw how naturally estate planning intersects with financial planning, insurance, and real estate — and wanted a structured way to build referral partnerships across those disciplines.',
    avatar: '/assets/illustrations/follow-the-leader-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/amarawilliamslaw',
    memberSince: '2023-03-01',
    clubSlugs: ['okc-south'],
    specialties: ['Wills & Trusts', 'Probate', 'Powers of Attorney', 'Business Succession Planning'],
  },
  {
    id: 'member-10',
    name: 'Carlos Mendez',
    slug: 'carlos-mendez',
    businessName: 'Mendez Financial Group',
    industry: 'Life & Health Insurance',
    industrySlug: 'life-health-insurance',
    role: 'Member',
    shortBio: 'Carlos helps individuals, families, and small business owners secure life, disability, and health insurance coverage.',
    bio: 'Carlos Mendez has been in the insurance industry for fourteen years, specializing in life insurance, disability income protection, and group health plans for small businesses. He joined ThinkBiz South because he wanted a community of trusted professionals he could confidently refer clients to — and who would return the favor. Carlos believes deeply in the educational component of networking and regularly brings guest speakers on financial protection topics to his chapter meetings.',
    avatar: '/assets/illustrations/business-flying.svg',
    linkedin: 'https://www.linkedin.com/in/carlosmendezinsurance',
    memberSince: '2023-06-15',
    clubSlugs: ['okc-south'],
    specialties: ['Life Insurance', 'Disability Insurance', 'Group Health Benefits', 'Key Person Coverage'],
  },
  {
    id: 'member-11',
    name: 'Jennifer Brooks',
    slug: 'jennifer-brooks',
    businessName: 'Brooks HR Consulting',
    industry: 'HR & Payroll Services',
    industrySlug: 'hr-payroll-services',
    role: 'Member',
    shortBio: 'Jennifer helps growing businesses manage HR compliance, payroll, and employee benefits without the overhead of a full HR department.',
    bio: 'Jennifer Brooks founded Brooks HR Consulting after spending twelve years as an HR director at a mid-size Oklahoma City company. She now works with small businesses that have outgrown informal people management but are not yet ready to hire a full-time HR professional. Her services range from employee handbooks and compliance audits to full payroll administration and benefits management. Jennifer joined ThinkBiz South because her ideal clients — growing businesses with 5 to 50 employees — are the same businesses that other members in the group serve.',
    avatar: '/assets/illustrations/excitement-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/jenniferbookshr',
    memberSince: '2023-09-01',
    clubSlugs: ['okc-south'],
    specialties: ['HR Compliance', 'Payroll Administration', 'Employee Handbooks', 'Benefits Management'],
  },
  {
    id: 'member-12',
    name: 'Mike Patterson',
    slug: 'mike-patterson',
    businessName: 'Patterson Home Services',
    industry: 'HVAC & Plumbing',
    industrySlug: 'hvac-plumbing',
    role: 'President',
    shortBio: 'Mike runs a residential and light commercial HVAC and plumbing company serving the Edmond and north OKC area.',
    bio: 'Mike Patterson founded Patterson Home Services twelve years ago with a single service van. Today his company runs a fleet of eight vehicles and serves hundreds of homeowners across Edmond and northern Oklahoma City. Mike joined the ThinkBiz Edmond chapter because he works alongside real estate agents, insurance agents, and contractors daily — and wanted a formalized system for turning those relationships into mutual referrals. He currently serves as Chapter President.',
    avatar: '/assets/illustrations/team-work-illustration.svg',
    linkedin: 'https://www.linkedin.com/in/mikepatersonhvac',
    memberSince: '2023-04-01',
    clubSlugs: ['edmond'],
    specialties: ['HVAC Installation', 'HVAC Repair', 'Plumbing', 'Water Heaters'],
    testimonial: 'I joined ThinkBiz Edmond because I knew the people in the room could send me work. What I did not expect was how much I would enjoy showing up every week.',
  },
  {
    id: 'member-13',
    name: 'Taylor Reed',
    slug: 'taylor-reed',
    businessName: 'Reed Photography & Video',
    industry: 'Photography & Videography',
    industrySlug: 'photography-videography',
    role: 'Member',
    shortBio: 'Taylor is a commercial photographer and videographer specializing in branding, headshots, and content for local businesses.',
    bio: 'Taylor Reed has been shooting commercial photography and video in the Oklahoma City area for eight years. Their work spans branding shoots, professional headshots, product photography, and short-form video for social media and websites. Taylor joined the Edmond chapter because they work with many of the same businesses as marketing consultants, web designers, and realtors — and found that referral networking was the most effective way to grow a creative services business sustainably.',
    avatar: '/assets/illustrations/leadership-growth.svg',
    linkedin: 'https://www.linkedin.com/in/taylorreedphoto',
    memberSince: '2023-07-01',
    clubSlugs: ['edmond'],
    specialties: ['Brand Photography', 'Headshots', 'Product Photography', 'Social Media Video'],
  },
]

// ─── CLUBS ─────────────────────────────────────────────────────────────────────

const OKC_NORTH_SEATS: IndustrySeat[] = [
  { industry: 'Web Design & Digital Marketing', industrySlug: 'web-design-digital-marketing', status: 'filled', memberId: 'member-1' },
  { industry: 'Accounting / CPA', industrySlug: 'accounting-cpa', status: 'filled', memberId: 'member-2' },
  { industry: 'Attorney — Business Law', industrySlug: 'attorney-business-law', status: 'filled', memberId: 'member-3' },
  { industry: 'Business & Commercial Insurance', industrySlug: 'business-commercial-insurance', status: 'filled', memberId: 'member-4' },
  { industry: 'Real Estate — Residential', industrySlug: 'real-estate-residential', status: 'filled', memberId: 'member-5' },
  { industry: 'Mortgage / Home Loans', industrySlug: 'mortgage-home-loans', status: 'filled', memberId: 'member-6' },
  { industry: 'Financial Planning & Wealth Management', industrySlug: 'financial-planning-wealth-management', status: 'filled', memberId: 'member-7' },
  { industry: 'HVAC & Plumbing', industrySlug: 'hvac-plumbing', status: 'open' },
  { industry: 'Recruiting & Staffing', industrySlug: 'recruiting-staffing', status: 'open' },
  { industry: 'Commercial Real Estate', industrySlug: 'commercial-real-estate', status: 'open' },
  { industry: 'Physical Therapy / Chiropractic', industrySlug: 'physical-therapy-chiropractic', status: 'open' },
  { industry: 'Title & Escrow', industrySlug: 'title-escrow', status: 'open' },
]

const OKC_SOUTH_SEATS: IndustrySeat[] = [
  { industry: 'Roofing & Exterior Services', industrySlug: 'roofing-exterior-services', status: 'filled', memberId: 'member-8' },
  { industry: 'Attorney — Estate Planning', industrySlug: 'attorney-estate-planning', status: 'filled', memberId: 'member-9' },
  { industry: 'Life & Health Insurance', industrySlug: 'life-health-insurance', status: 'filled', memberId: 'member-10' },
  { industry: 'HR & Payroll Services', industrySlug: 'hr-payroll-services', status: 'filled', memberId: 'member-11' },
  { industry: 'Accounting / CPA', industrySlug: 'accounting-cpa', status: 'open' },
  { industry: 'Mortgage / Home Loans', industrySlug: 'mortgage-home-loans', status: 'open' },
  { industry: 'Real Estate — Residential', industrySlug: 'real-estate-residential', status: 'open' },
  { industry: 'Web Design & Digital Marketing', industrySlug: 'web-design-digital-marketing', status: 'open' },
  { industry: 'Financial Planning & Wealth Management', industrySlug: 'financial-planning-wealth-management', status: 'open' },
  { industry: 'Commercial Cleaning', industrySlug: 'commercial-cleaning', status: 'open' },
]

const EDMOND_SEATS: IndustrySeat[] = [
  { industry: 'HVAC & Plumbing', industrySlug: 'hvac-plumbing', status: 'filled', memberId: 'member-12' },
  { industry: 'Photography & Videography', industrySlug: 'photography-videography', status: 'filled', memberId: 'member-13' },
  { industry: 'Accounting / CPA', industrySlug: 'accounting-cpa', status: 'open' },
  { industry: 'Attorney — Business Law', industrySlug: 'attorney-business-law', status: 'open' },
  { industry: 'Business & Commercial Insurance', industrySlug: 'business-commercial-insurance', status: 'open' },
  { industry: 'Real Estate — Residential', industrySlug: 'real-estate-residential', status: 'open' },
  { industry: 'Mortgage / Home Loans', industrySlug: 'mortgage-home-loans', status: 'open' },
  { industry: 'Financial Planning & Wealth Management', industrySlug: 'financial-planning-wealth-management', status: 'open' },
  { industry: 'Landscaping & Lawn Care', industrySlug: 'landscaping-lawn-care', status: 'open' },
  { industry: 'Personal Training / Fitness', industrySlug: 'personal-training-fitness', status: 'open' },
]

export const CLUBS: Club[] = [
  {
    id: 'club-1',
    name: 'OKC North Chapter',
    slug: 'okc-north',
    chapter: 'Chapter 1',
    city: 'Oklahoma City',
    area: 'North Oklahoma City',
    address: '3810 N Tulsa Ave, Oklahoma City, OK 73112',
    venueName: 'The Meeting Room at Tulsa Ave',
    meetingDay: 'Tuesday',
    meetingTime: '7:30 AM',
    meetingFrequency: 'Weekly',
    shortDescription: 'Our founding chapter — a tight-knit group of OKC professionals meeting every Tuesday morning to grow through referrals.',
    description: 'The OKC North Chapter is the original ThinkBiz.Solutions chapter, established in 2022. This group of established professionals meets every Tuesday morning and has built one of the most active referral cultures in our network. Members span a wide range of complementary industries, creating a high volume of relevant, quality referrals week over week. There are still a handful of open seats available for the right professionals.',
    featureImage: '/assets/illustrations/team-work-illustration.svg',
    mapUrl: 'https://maps.google.com/?q=3810+N+Tulsa+Ave+Oklahoma+City+OK+73112',
    established: '2022',
    memberCount: 7,
    openSeats: 5,
    seats: OKC_NORTH_SEATS,
    memberIds: ['member-1', 'member-2', 'member-3', 'member-4', 'member-5', 'member-6', 'member-7'],
    presidentId: 'member-1',
  },
  {
    id: 'club-2',
    name: 'OKC South Chapter',
    slug: 'okc-south',
    chapter: 'Chapter 2',
    city: 'Oklahoma City',
    area: 'South Oklahoma City',
    address: '1221 SW 44th St, Oklahoma City, OK 73119',
    venueName: 'Southside Business Center',
    meetingDay: 'Wednesday',
    meetingTime: '12:00 PM',
    meetingFrequency: 'Weekly',
    shortDescription: 'A growing midday chapter on the south side of OKC, with several high-value seats still available.',
    description: 'The OKC South Chapter launched in early 2023 and has quickly built a reputation for energy and accountability. This chapter meets every Wednesday at noon, making it an ideal fit for professionals whose mornings are less flexible. With several open seats available across high-demand categories, this is an excellent time to get established in a group that is still building its foundation.',
    featureImage: '/assets/illustrations/follow-the-leader-illustration.svg',
    mapUrl: 'https://maps.google.com/?q=1221+SW+44th+St+Oklahoma+City+OK+73119',
    established: '2023',
    memberCount: 4,
    openSeats: 6,
    seats: OKC_SOUTH_SEATS,
    memberIds: ['member-8', 'member-9', 'member-10', 'member-11'],
    presidentId: 'member-8',
  },
  {
    id: 'club-3',
    name: 'Edmond Chapter',
    slug: 'edmond',
    chapter: 'Chapter 3',
    city: 'Edmond',
    area: 'Edmond, OK',
    address: '14 E 1st St, Edmond, OK 73034',
    venueName: 'Edmond Community Hub',
    meetingDay: 'Thursday',
    meetingTime: '7:30 AM',
    meetingFrequency: 'Weekly',
    shortDescription: 'Edmond\'s dedicated ThinkBiz chapter — early morning meetings for professionals who want to grow locally.',
    description: 'The Edmond Chapter was established in 2023 to serve the thriving business community in Edmond and surrounding areas. This Thursday morning chapter is actively recruiting members across most professional categories. If you serve Edmond-area clients and want to build referral relationships with other trusted local professionals, this chapter has room for you.',
    featureImage: '/assets/illustrations/leadership-growth.svg',
    mapUrl: 'https://maps.google.com/?q=14+E+1st+St+Edmond+OK+73034',
    established: '2023',
    memberCount: 2,
    openSeats: 8,
    seats: EDMOND_SEATS,
    memberIds: ['member-12', 'member-13'],
    presidentId: 'member-12',
  },
]

// ─── HELPER FUNCTIONS ─────────────────────────────────────────────────────────

export function getClubBySlug(slug: string): Club | undefined {
  return CLUBS.find((c) => c.slug === slug)
}

export function getMemberBySlug(slug: string): ClubMember | undefined {
  return CLUB_MEMBERS.find((m) => m.slug === slug)
}

export function getMemberById(id: string): ClubMember | undefined {
  return CLUB_MEMBERS.find((m) => m.id === id)
}

export function getClubMembers(club: Club): ClubMember[] {
  return club.memberIds
    .map((id) => getMemberById(id))
    .filter((m): m is ClubMember => m !== undefined)
}

export function getMemberClubs(member: ClubMember): Club[] {
  return CLUBS.filter((c) => member.clubSlugs.includes(c.slug))
}

export function getClubsForCity(city: string): Club[] {
  return CLUBS.filter((c) => c.city.toLowerCase() === city.toLowerCase())
}

export function getOpenSeats(club: Club) {
  return club.seats.filter((s) => s.status === 'open')
}

export function getFilledSeats(club: Club) {
  return club.seats.filter((s) => s.status === 'filled')
}
